plugins:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "tmp/**/*"
    - vendor/bundle/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 3

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*"

RSpec/LeakyConstantDeclaration:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

RSpec/MultipleMemoizedHelpers:
  Max: 7

Style/Documentation:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/NestedGroups:
  Max: 5